// <auto-generated />
namespace Fashion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class version_113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_113));
        
        string IMigrationMetadata.Id
        {
            get { return "202110300638179_version_1.1.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
