// <auto-generated />
namespace Fashion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class version_105 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_105));
        
        string IMigrationMetadata.Id
        {
            get { return "202107250315107_version_1.0.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
