// <auto-generated />
namespace Fashion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class version_108 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_108));
        
        string IMigrationMetadata.Id
        {
            get { return "202107260914186_version_1.0.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
